2024-01-16 22:30:29,338 (3fa56010) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: cc260c4 (Fri Dec 14 20:14:21 UTC 2018)
2024-01-16 22:30:29,341 (3fa56010) :  DEBUG (core:361) - Using the standard policy
2024-01-16 22:30:29,342 (3fa56010) :  DEBUG (core:450) - Starting runtime component.
2024-01-16 22:30:29,361 (3fa56010) :  DEBUG (core:450) - Starting caching component.
2024-01-16 22:30:29,362 (3fa56010) :  DEBUG (core:450) - Starting data component.
2024-01-16 22:30:29,363 (3fa56010) :  DEBUG (core:450) - Starting networking component.
2024-01-16 22:30:29,364 (3fa56010) :  DEBUG (networking:288) - No cookie jar found
2024-01-16 22:30:29,368 (3fa56010) :  DEBUG (networking:452) - Setting the default network timeout to 20.0
2024-01-16 22:30:29,371 (3fa56010) :  DEBUG (core:450) - Starting localization component.
2024-01-16 22:30:29,372 (3fa56010) :  INFO (localization:409) - Setting the default locale to en-us
2024-01-16 22:30:29,373 (3fa56010) :  DEBUG (core:450) - Starting messaging component.
2024-01-16 22:30:29,376 (3fa56010) :  DEBUG (core:450) - Starting debugging component.
2024-01-16 22:30:29,377 (3fa56010) :  DEBUG (core:450) - Starting services component.
2024-01-16 22:30:29,378 (392ff460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.movieposterdb'
2024-01-16 22:30:29,378 (3fa56010) :  DEBUG (core:450) - Starting myplex component.
2024-01-16 22:30:29,383 (3fa56010) :  DEBUG (core:450) - Starting notifications component.
2024-01-16 22:30:29,858 (3fa56010) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.movieposterdb in namespace 'metadata'
2024-01-16 22:30:29,877 (3fa56010) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2024-01-16 22:30:29,895 (3fa56010) :  ERROR (networking:219) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2024-01-16 22:30:29,899 (3fa56010) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 265, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 243, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 181, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 444, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 557, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 482, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 416, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-cc260c476/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/urllib2_new.py", line 565, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2024-01-16 22:30:29,927 (392ff460) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2024-01-16 22:30:29,928 (3fa56010) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2024-01-16 22:30:29,937 (3fa56010) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2024-01-16 22:30:29,938 (392ff460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2024-01-16 22:30:29,940 (37dff460) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400'
2024-01-16 22:30:29,944 (3fa56010) :  DEBUG (core:150) - Finished starting framework core
2024-01-16 22:30:29,944 (3fa56010) :  DEBUG (core:560) - Loading plug-in code
2024-01-16 22:30:30,030 (3fa56010) :  DEBUG (core:566) - Finished loading plug-in code
2024-01-16 22:30:30,034 (3fa56010) :  DEBUG (agentkit:1115) - Creating new agent class called CineMaterialAgent
2024-01-16 22:30:30,036 (37dff460) :  DEBUG (core:538) - Machine identifier is a08675478bee93f590cc67146fe0b3ee6f493f1f
2024-01-16 22:30:30,037 (3fa56010) :  DEBUG (agentkit:933) - Updating agent information: [{'media_types': ['Movie'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': ['com.plexapp.agents.imdb'], 'languages': ['xn'], 'persist_stored_files': True, 'version': 0, 'primary_provider': False, 'prefs': False, 'name': 'CineMaterial'}]
2024-01-16 22:30:30,038 (37dff460) :  DEBUG (core:539) - Server version is 1.14.1.5488-cc260c476
2024-01-16 22:30:30,044 (392ff460) :  DEBUG (services:362) - Loaded services
2024-01-16 22:30:30,048 (3fa56010) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo2CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdApsaXN0CjIKczMyCmNvbS5wbGV4YXBwLmFnZW50cy5tb3ZpZXBvc3RlcmRiczEwCmlkZW50aWZpZXJyMQpzMTAKYWdlbnRfaW5mbzEKcjIKMTAKcjMKczExCm1lZGlhX3R5cGVzbnMxMgphY2NlcHRzX2Zyb21uczE0CmZhbGxiYWNrX2FnZW50cjQKczE0CmNvbnRyaWJ1dGVzX3RvcjUKczkKbGFuZ3VhZ2VzYjFzMjAKcGVyc2lzdF9zdG9yZWRfZmlsZXNpMApzNwp2ZXJzaW9uYjBzMTYKcHJpbWFyeV9wcm92aWRlcmIwczUKcHJlZnNzMTIKQ2luZU1hdGVyaWFsczQKbmFtZTEKczUKTW92aWUxCnMyMwpjb20ucGxleGFwcC5hZ2VudHMuaW1kYjEKczIKeG5yMAo_'
2024-01-16 22:30:30,062 (387bf460) :  DEBUG (services:438) - No shared code to load
2024-01-16 22:30:30,093 (3fa56010) :  INFO (core:611) - Started plug-in
2024-01-16 22:30:30,094 (3fa56010) :  DEBUG (socketinterface:160) - Starting socket server
2024-01-16 22:30:30,099 (3fa56010) :  DEBUG (runtime:1117) - Created a thread named 'start'
2024-01-16 22:30:30,101 (3fa56010) :  INFO (socketinterface:184) - Socket server started on port 40911
2024-01-16 22:30:30,102 (3fa56010) :  INFO (pipeinterface:25) - Entering run loop
2024-01-16 22:30:30,104 (3fa56010) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2024-01-16 22:30:30,109 (3fa56010) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2024-01-16 22:30:30,114 (3fa56010) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 157 bytes
